version: "3.9"

services:
  # MSSQL Server
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - mssql_data:/var/opt/mssql

  # RabbitMQ (с панелью управления)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    networks:
      - backend

  # Redis
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  # AuthService
  authservice:
    build:
      context: .
      dockerfile: PS.FreeBookHub_Lite.AuthService.API/Dockerfile
    container_name: authservice
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - mssql
    networks:
      - backend

  # CartService
  cartservice:
    build:
      context: .
      dockerfile: PS.FreeBookHub_Lite.CartService.API/Dockerfile
    container_name: cartservice
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - mssql
      - catalogservice
      - orderservice
    networks:
      - backend

  # CatalogService
  catalogservice:
    build:
      context: .
      dockerfile: PS.FreeBookHub_Lite.CatalogService.API/Dockerfile
    container_name: catalogservice
    ports:
      - "5002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - mssql
    networks:
      - backend

  # OrderService
  orderservice:
    build:
      context: .
      dockerfile: PS.FreeBookHub_Lite.OrderService.API/Dockerfile
    container_name: orderservice
    ports:
      - "5003:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - mssql
      - rabbitmq
      - redis
      - paymentservice
    networks:
      - backend

  # PaymentService
  paymentservice:
    build:
      context: .
      dockerfile: PS.FreeBookHub_Lite.PaymentService.API/Dockerfile
    container_name: paymentservice
    ports:
      - "5004:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - mssql
      - rabbitmq
      - redis
    networks:
      - backend

networks:
  backend:

volumes:
  mssql_data:
